services:
  sim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mavros_sim
    privileged: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev/dri:/dev/dri
      - ./src:/root/catkin_ws/src:ro
    stdin_open: true
    tty: true